require("../db");
const mongoose = require("mongoose");
const RecipeModel = require("../models/Recipe.model.js");

RecipeModel.create([
  {
    name: "Bakewell tart",
    ingredients: [
      "plain flour: 175g",
      "chilled butter: 75g",
      "cold water: 75g",
      "raspberry jam: 2-3 tbsp",
      "butter: 1 tbsp",
      "caster sugar: 125g",
      "ground almonds: 125g",
      "free-range egg, beaten: 125g",
      "almond extract: ½ tsp",
      "flaked almonds: 50g",
    ],
    instructions:
      "To make the pastry, measure the flour into a bowl and rub in the butter with your fingertips until the mixture resembles fine breadcrumbs. Add the water, mixing to form a soft dough. Roll out the dough on a lightly floured work surface and use to line a 20cm/8in flan tin. Leave in the fridge to chill for 30 minutes. Preheat the oven to 200C/400F/Gas 6 (180C fan). Line the pastry case with foil and fill with baking beans. Bake blind for about 15 minutes, then remove the beans and foil and cook for a further five minutes to dry out the base. For the filing, spread the base of the flan generously with raspberry jam. Melt the butter in a pan, take off the heat and then stir in the sugar. Add ground almonds, egg and almond extract. Pour into the flan tin and sprinkle over the flaked almonds. Bake for about 35 minutes. If the almonds seem to be browning too quickly, cover the tart loosely with foil to prevent them burning.",
    youtube: "https://www.youtube.com/watch?v=1ahpSTf_Pvk",
    image: "https://www.themealdb.com/images/media/meals/wyrqqq1468233628.jpg",
    description:
      "A Bakewell tart is an English confection consisting of a shortcrust pastry shell beneath layers of jam, frangipane, and a topping of flaked almonds.",
    cookingTime: 150,
    difficulty: "Medium",
    created_by: "Admin",
    country: "UK",
    category: "Dessert",
    vegetarian: true,
  },
  {
    name: "Baingan Bharta",
    ingredients: [
      "Aubergine: 1 large",
      "Onion: ½ cup",
      "Tomatoes: 1 cup",
      "Garlic: 6 cloves",
      "Green Chili: 1",
      "Red Chili Powder: ¼ teaspoon",
      "Oil: 1.5 tablespoon",
      "Coriander Leaves: 1.5 tablespoon",
      "salt: as required",
    ],
    instructions:
      "Rinse the baingan (eggplant or aubergine) in water. Pat dry with a kitchen napkin. Apply some oil all over and keep it for roasting on an open flame. You can also grill the baingan or roast in the oven. But then you won't get the smoky flavor of the baingan. Keep the eggplant turning after a 2 to 3 minutes on the flame, so that its evenly cooked. You could also embed some garlic cloves in the baingan and then roast it. 2. Roast the aubergine till its completely cooked and tender. With a knife check the doneness. The knife should slid easily in aubergines without any resistance. Remove the baingan and immerse in a bowl of water till it cools down. 3. You can also do the dhungar technique of infusing charcoal smoky flavor in the baingan. This is an optional step. Use natural charcoal for this method. Heat a small piece of charcoal on flame till it becomes smoking hot and red. 4. Make small cuts on the baingan with a knife. Place the red hot charcoal in the same plate where the roasted aubergine is kept. Add a few drops of oil on the charcoal. The charcoal would begin to smoke. 5. As soon as smoke begins to release from the charcoal, cover the entire plate tightly with a large bowl. Allow the charcoal smoke to get infused for 1 to 2 minutes. The more you do, the more smoky the baingan bharta will become. I just keep for a minute. Alternatively, you can also do this dhungar method once the baingan bharta is cooked, just like the way we do for Dal Tadka. 6. Peel the skin from the roasted and smoked eggplant. 7. Chop the cooked eggplant finely or you can even mash it. 8. In a kadai or pan, heat oil. Then add finely chopped onions and garlic. 9. Saute the onions till translucent. Don't brown them. 10. Add chopped green chilies and saute for a minute. 11. Add the chopped tomatoes and mix it well. 12. Bhuno (saute) the tomatoes till the oil starts separating from the mixture. 13. Now add the red chili powder. Stir and mix well. 14. Add the chopped cooked baingan. 15. Stir and mix the chopped baingan very well with the onion­tomato masala mixture. 16. Season with salt. Stir and saute for some more 4 to 5 minutes more. 17. Finally stir in the coriander leaves with the baingan bharta or garnish it with them. Serve Baingan Bharta with phulkas, rotis or chapatis. It goes well even with bread, toasted or grilled bread and plain rice or jeera rice.",
    youtube: "https://www.youtube.com/watch?v=-84Zz2EP4h4",
    image: "https://www.themealdb.com/images/media/meals/urtpqw1487341253.jpg",
    description:
      "Baingan bharta (mashed eggplant) is a South Asian dish prepared by mincing grilled eggplant (baingan) and mixing it with tomato, onion, herbs and spices.",
    cookingTime: 30,
    difficulty: "Easy",
    created_by: "Admin",
    country: "India",
    category: "Main course",
    vegetarian: true,
  },
  {
    name: "Beef stroganoff",
    ingredients: [
      "Olive Oil: 1 tbls",
      "Onion: 1",
      "Garlic: 1 clove",
      "Butter: 1 tbsp",
      "Mushrooms: 250g",
      "Beef Fillet: 500g",
      "Plain Flour: 1tbsp",
      "Creme Fraiche: 150g",
      "English Mustard: 1 tbsp",
      "Beef Stock: 100ml",
      "Parsley: topping",
    ],
    instructions:
      "Heat the olive oil in a non-stick frying pan then add the sliced onion and cook on a medium heat until completely softened, so around 15 mins, adding a little splash of water if they start to stick at all. Crush in the garlic and cook for a 2-3 mins further, then add the butter. Once the butter is foaming a little, add the mushrooms and cook for around 5 mins until completely softened. Season everything well, then tip onto a plate. Tip the flour into a bowl with a big pinch of salt and pepper, then toss the steak in the seasoned flour. Add the steak pieces to the pan, splashing in a little oil if the pan looks particularly dry, and fry for 3-4 mins, until well coloured. Tip the onions and mushrooms back into the pan. Whisk the crème fraîche, mustard and beef stock together, then pour into the pan. Cook over a medium heat for around 5 mins. Scatter with parsley, then serve with pappardelle or rice.",
    youtube: "https://www.youtube.com/watch?v=PQHgQX1Ss74",
    image: "https://www.themealdb.com/images/media/meals/svprys1511176755.jpg",
    description:
      "Beef Stroganoff or Beef Stroganov (Russian: бефстроганов, tr. befstróganov[1]) is a Russian dish of sautéed pieces of beef served in a sauce with smetana (sour cream).",
    cookingTime: 60,
    difficulty: "Easy",
    created_by: "Admin",
    country: "Russia",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Banana Pancakes",
    ingredients: [
      "Banana: 1 large",
      "Eggs: 2 medium",
      "Baking Powder: pinch",
      "Vanilla Extract: spinkling",
      "Oil: 1 tsp",
      "Pecan Nuts: 25g",
      "Raspberries: 125g",
    ],
    instructions:
      "In a bowl, mash the banana with a fork until it resembles a thick purée. Stir in the eggs, baking powder and vanilla. Heat a large non-stick frying pan or pancake pan over a medium heat and brush with half the oil. Using half the batter, spoon two pancakes into the pan, cook for 1-2 mins each side, then tip onto a plate. Repeat the process with the remaining oil and batter. Top the pancakes with the pecans and raspberries.",
    youtube: "https://www.youtube.com/watch?v=kSKtb2Sv-_U",
    image: "https://www.themealdb.com/images/media/meals/sywswr1511383814.jpg",
    description:
      "A pancake (or hotcake, griddlecake, or flapjack, not to be confused with oat bar flapjacks) is a flat cake, often thin and round, prepared from a starch-based batter that may contain eggs, milk and butter and cooked on a hot surface such as a griddle or frying pan, often frying with oil or butter.",
    cookingTime: 15,
    difficulty: "Easy",
    created_by: "Admin",
    country: "USA",
    category: "Breakfast",
    vegetarian: true,
  },
  {
    name: "Brown Stew Chicken",
    ingredients: [
      "Chicken: 1 whole",
      "Tomato: 1 chopped",
      "Onions: 2 chopped",
      "Garlic Clove: 2 chopped",
      "Red Pepper: 1 chopped",
      "Carrots: 1 chopped",
      "Lime: 1",
      "Thyme: 2 tsp",
      "Allspice: 1 tsp",
      "Soy Sauce: 2 tbs",
      "Cornstarch: 2 tsp",
      "Coconut Milk: 2 cups",
      "Vegetable Oil: 1 tbs",
    ],
    instructions:
      "Squeeze lime over chicken and rub well. Drain off excess lime juice. Combine tomato, scallion, onion, garlic, pepper, thyme, pimento and soy sauce in a large bowl with the chicken pieces. Cover and marinate at least one hour. Heat oil in a dutch pot or large saucepan. Shake off the seasonings as you remove each piece of chicken from the marinade. Reserve the marinade for sauce. Lightly brown the chicken a few pieces at a time in very hot oil. Place browned chicken pieces on a plate to rest while you brown the remaining pieces. Drain off excess oil and return the chicken to the pan. Pour the marinade over the chicken and add the carrots. Stir and cook over medium heat for 10 minutes. Mix flour and coconut milk and add to stew, stirring constantly. Turn heat down to minimum and cook another 20 minutes or until tender.",
    youtube: "https://www.youtube.com/watch?v=_gFB1fkNhXs",
    image: "https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg",
    description:
      "Brown stew chicken, also referred to as stew chicken, is a dish typically eaten for dinner throughout the English speaking Caribbean islands. The dish is popular in Jamaica, Antigua, Trinidad and Tobago, Barbados, Saint Lucia, Grenada, Belize, Dominica and in Caribbean communities throughout the world.",
    cookingTime: 840,
    difficulty: "Hard",
    created_by: "Admin",
    country: "Jamaica",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Bitterballen (Dutch meatballs)",
    ingredients: [
      "Butter: 100g",
      "Flour: 150g",
      "Beef Stock: 700ml",
      "Onion: 30g",
      "Parsley: 1 tbs",
      "Beef: 400g",
      "Salt: Pinch",
      "Pepper: Pinch",
      "Nutmeg: Pinch",
      "Flour: 50g",
      "Eggs: 2 Beaten",
      "Breadcrumbs: 50g",
    ],
    instructions:
      "Melt the butter in a skillet or pan. When melted, add the flour little by little and stir into a thick paste. Slowly stir in the stock, making sure the roux absorbs the liquid. Simmer for a couple of minutes on a low heat while you stir in the onion, parsley and the shredded meat. The mixture should thicken and turn into a heavy, thick sauce. Pour the mixture into a shallow container, cover and refrigerate for several hours, or until the sauce has solidified. Take a heaping tablespoon of the cold, thick sauce and quickly roll it into a small ball. Roll lightly through the flour, then the egg and finally the breadcrumbs. Make sure that the egg covers the whole surface of the bitterbal. When done, refrigerate the snacks while the oil in your fryer heats up to 190C (375F). Fry four bitterballen at a time, until golden. Serve on a plate with a nice grainy or spicy mustard. ",
    youtube: "https://www.youtube.com/watch?v=q8AKfYUtDuM",
    image: "https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg",
    description:
      "Bitterballen (plural of bitterbal) are a Dutch meat-based snack, made by making a very thick stew thickened with roux and beef stock and generously loaded with meat, refrigerating the stew until it firms, and then rolling the thick mixture into balls which then get breaded and fried.",
    cookingTime: 20,
    difficulty: "Easy",
    created_by: "Admin",
    country: "Netherlands",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Bigos (Hunters Stew)",
    ingredients: [
      "Bacon: 2 sliced",
      "Kielbasa: 1 lb",
      "Pork: 1 lb",
      "Flour: 1/4 cup",
      "Garlic: 3 chopped",
      "Onion: 1 Diced",
      "Mushrooms: 1 1/2 cup",
      "Cabbage: 4 cups",
      "Sauerkraut: 1 Jar",
      "Red Wine: 1/4 cup",
      "Bay Leaf: 1",
      "Basil: 1 tsp",
      "Marjoram: 1 tsp",
      "Paprika: 1 tbs",
      "Caraway Seed: 1/8 teaspoon",
      "Hotsauce: 1 dash",
      "Beef Stock: 5 Cups",
      "Tomato Puree: 2 tbs",
      "Diced Tomatoes: 1 cup",
      "Worcestershire Sauce: 1 dash",
    ],
    instructions:
      "Preheat the oven to 350 degrees F (175 degrees C). Heat a large pot over medium heat. Add the bacon and kielbasa; cook and stir until the bacon has rendered its fat and sausage is lightly browned. Use a slotted spoon to remove the meat and transfer to a large casserole or Dutch oven. Coat the cubes of pork lightly with flour and fry them in the bacon drippings over medium-high heat until golden brown. Use a slotted spoon to transfer the pork to the casserole. Add the garlic, onion, carrots, fresh mushrooms, cabbage and sauerkraut. Reduce heat to medium; cook and stir until the carrots are soft, about 10 minutes. Do not let the vegetables brown. Deglaze the pan by pouring in the red wine and stirring to loosen all of the bits of food and flour that are stuck to the bottom. Season with the bay leaf, basil, marjoram, paprika, salt, pepper, caraway seeds and cayenne pepper; cook for 1 minute. Mix in the dried mushrooms, hot pepper sauce, Worcestershire sauce, beef stock, tomato paste and tomatoes. Heat through just until boiling. Pour the vegetables and all of the liquid into the casserole dish with the meat. Cover with a lid. Bake in the preheated oven for 2 1/2 to 3 hours, until meat is very tender.",
    youtube: "https://www.youtube.com/watch?v=Oqg_cO4s8ik",
    image: "https://www.themealdb.com/images/media/meals/md8w601593348504.jpg",
    description:
      "Bigos, often translated into English as hunter's stew, is a Polish dish of chopped meat of various kinds stewed with sauerkraut and shredded fresh cabbage. It is served hot and can be enriched with vegetables, spices or wine.",
    cookingTime: 210,
    difficulty: "Medium",
    created_by: "Admin",
    country: "Poland",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Boxty Breakfast",
    ingredients: [
      "Potatoes: 4 large",
      "Spring Onions: 1 bunch",
      "Plain Flour: 100g",
      "Egg White: 1",
      "Milk: 150ml",
      "Bicarbonate Of Soda: 1 tsp",
      "Butter: 3 tbs",
      "Vegetable Oil: 2 tbs",
      "Cherry Tomatoes: 6",
      "Bacon: 12",
      "Egg: 6",
    ],
    instructions:
      "STEP 1 Before you start, put your oven on its lowest setting, ready to keep things warm. Peel the potatoes, grate 2 of them, then set aside. Cut the other 2 into large chunks, then boil for 10-15 mins or until tender. Meanwhile, squeeze as much of the liquid from the grated potatoes as you can using a clean tea towel. Mash the boiled potatoes, then mix with the grated potato, spring onions and flour. STEP 2 Whisk the egg white in a large bowl until it holds soft peaks. Fold in the buttermilk, then add the bicarbonate of soda. Fold into the potato mix. STEP 3 Heat a large non-stick frying pan over a medium heat, then add 1 tbsp butter and some of the oil. Drop 3-4 spoonfuls of the potato mixture into the pan, then gently cook for 3-5 mins on each side until golden and crusty. Keep warm on a plate in the oven while you cook the next batch, adding more butter and oil to the pan before you do so. You will get 16 crumpet-size boxty from the mix. Can be made the day ahead, drained on kitchen paper, then reheated in a low oven for 20 mins. STEP 4 Heat the grill to medium and put the tomatoes in a heavy-based pan. Add a good knob of butter and a little oil, then fry for about 5 mins until softened. Grill the bacon, then pile onto a plate and keep warm. Stack up the boxty, bacon and egg, and serve the tomatoes on the side.",
    youtube: "https://www.youtube.com/watch?v=80W0mCFDIP0",
    image: "https://www.themealdb.com/images/media/meals/naqyel1608588563.jpg",
    description:
      "Boxty (Irish: bacstaí) is a traditional Irish potato pancake.",
    cookingTime: 30,
    difficulty: "Easy",
    created_by: "Admin",
    country: "Ireland",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Beef Rendang",
    ingredients: [
      "Beef: 1lb",
      "Vegetable Oil: 5 tbs",
      "Cinnamon Stick: 1",
      "Cloves: 3",
      "Star Anise: 3",
      "Cardamom: 3",
      "Coconut Cream: 1 cup",
      "Water: 1 cup",
      "Tamarind Paste: 2 tbs",
      "Lime: 6",
      "Sugar: 1 tbs",
      "Challots: 5",
    ],
    instructions:
      "Chop the spice paste ingredients and then blend it in a food processor until fine. Heat the oil in a stew pot, add the spice paste, cinnamon, cloves, star anise, and cardamom and stir-fry until aromatic. Add the beef and the pounded lemongrass and stir for 1 minute. Add the coconut milk, tamarind juice, water, and simmer on medium heat, stirring frequently until the meat is almost cooked. Add the kaffir lime leaves, kerisik (toasted coconut), sugar or palm sugar, stirring to blend well with the meat. Lower the heat to low, cover the lid, and simmer for 1 to 1 1/2 hours or until the meat is really tender and the gravy has dried up. Add more salt and sugar to taste. Serve immediately with steamed rice and save some for overnight.",
    youtube: "https://www.youtube.com/watch?v=Ot-dmfBaZrA",
    image: "https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg",
    description:
      "As the signature dish of Minangkabau culture, rendang is traditionally served at ceremonial occasions to honour guests during festive events.",
    cookingTime: 210,
    difficulty: "Medium",
    created_by: "Admin",
    country: "Malaysia",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Chicken Enchilada Casserole",
    ingredients: [
      "Enchilada sauce: 14 oz jar",
      "shredded Monterey Jack cheese: 3 Cups",
      "corn tortillas: 6",
      "chicken breasts: 2",
    ],
    instructions:
      "Cut each chicken breast in about 3 pieces, so that it cooks faster and put it in a small pot. Pour Enchilada sauce over it and cook covered on low to medium heat until chicken is cooked through, about 20 minutes. No water is needed, the chicken will cook in the Enchilada sauce. Make sure you stir occasionally so that it doesn't stick to the bottom. Remove chicken from the pot and shred with two forks. Preheat oven to 375 F degrees. Start layering the casserole. Start with about ¼ cup of the leftover Enchilada sauce over the bottom of a baking dish. I used a longer baking dish, so that I can put 2 corn tortillas across. Place 2 tortillas on the bottom, top with ⅓ of the chicken and ⅓ of the remaining sauce. Sprinkle with ⅓ of the cheese and repeat starting with 2 more tortillas, then chicken, sauce, cheese. Repeat with last layer with the remaining ingredients, tortillas, chicken, sauce and cheese. Bake for 20 to 30 minutes uncovered, until bubbly and cheese has melted and started to brown on top. Serve warm.",
    youtube: "https://www.youtube.com/watch?v=EtVkwVKLc_M",
    image: "https://www.themealdb.com/images/media/meals/qtuwxu1468233098.jpg",
    description: "",
    cookingTime: 60,
    difficulty: "Easy",
    created_by: "Admin",
    country: "Mexico",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Chicken Alfredo Primavera",
    ingredients: [
      "Butter: 2 tablespoons",
      "Olive Oil: 3 tablespoons",
      "Chicken: 5 boneless",
      "Salt: 1 teaspoon",
      "Squash: 1 cut into 1/2-inch cubes",
      "Broccoli: 1 Head chopped",
      "mushrooms: 8-ounce sliced",
      "Pepper: 1 red",
      "onion: 1 chopped",
      "garlic: 3 cloves",
      "red pepper flakes: 1/2 teaspoon",
      "white wine: 1/2 cup",
      "milk: 1/2 cup",
      "heavy cream: 1/2 cup",
      "Parmesan cheese: 1 cup grated",
      "bowtie pasta: 16 ounces",
      "Salt: pinch",
      "Pepper: pinch",
      "Parsley: chopped",
    ],
    instructions:
      "Heat 1 tablespoon of butter and 2 tablespoons of olive oil in a large skillet over medium-high heat. Season both sides of each chicken breast with seasoned salt and a pinch of pepper. Add the chicken to the skillet and cook for 5-7 minutes on each side, or until cooked through. While the chicken is cooking, bring a large pot of water to a boil. Season the boiling water with a few generous pinches of kosher salt. Add the pasta and give it a stir. Cook, stirring occasionally, until al dente, about 12 minutes. Reserve 1/2 cup of pasta water before draining the pasta. Remove the chicken from the pan and transfer it to a cutting board; allow it to rest. Turn the heat down to medium and dd the remaining 1 tablespoon of butter and olive oil to the same pan you used to cook the chicken. Add the veggies (minus the garlic) and red pepper flakes to the pan and stir to coat with the oil and butter (refrain from seasoning with salt until the veggies are finished browning). Cook, stirring often, until the veggies are tender, about 5 minutes. Add the garlic and a generous pinch of salt and pepper to the pan and cook for 1 minute. Deglaze the pan with the white wine. Continue to cook until the wine has reduced by half, about 3 minutes. Stir in the milk, heavy cream, and reserved pasta water. Bring the mixture to a gentle boil and allow to simmer and reduce for 2-3 minutes. Turn off the heat and add the Parmesan cheese and cooked pasta. Season with salt and pepper to taste. Garnish with Parmesan cheese and chopped parsley, if desired. ",
    youtube: "https://www.youtube.com/watch?v=qCIbq8HywpQ",
    image: "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
    description:
      "Fettuccine Alfredo is an Italian pasta dish of fresh fettuccine tossed with butter and Parmesan cheese.",
    cookingTime: 50,
    difficulty: "Medium",
    created_by: "Admin",
    country: "Italia",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Duck Confit",
    ingredients: [
      "Sea Salt: Handful",
      "Bay Leaf: 4",
      "Garlic: 4",
      "Thyme: Handful",
      "Duck Legs: 4",
      "White Wine: 100ml",
    ],
    instructions:
      "The day before you want to make the dish, scatter half the salt, half the garlic and half of the herbs over the base of a small shallow dish. Lay the duck legs, skin-side up, on top, then scatter over the remaining salt, garlic and herbs. Cover the duck and refrigerate overnight. This can be done up to 2 days ahead. Pour the wine into a saucepan that will snugly fit the duck legs in a single layer. Brush the salt off the duck legs and place them, skin-side down, in the wine. Cover the pan with a lid and place over a medium heat. As soon as the wine starts to bubble, turn the heat down to the lowest setting and cook for 2 hours, checking occasionally that the liquid is just barely simmering. (If you own a heat diffuser, it would be good to use it here.) After 2 hours, the duck legs should be submerged in their own fat and the meat should feel incredibly tender when prodded. Leave to cool. The duck legs are now cooked and can be eaten immediately – or you can follow the next step if you like them crisp. If you are preparing ahead, pack the duck legs tightly into a plastic container or jar and pour over the fat, but not the liquid at the bottom of the pan. Cover and leave in the fridge for up to a month, or freeze for up to 3 months. The liquid you are left with makes a tasty gravy, which can be chilled or frozen until needed. To reheat and crisp up the duck legs, heat oven to 220C/fan 200C/gas 7. Remove the legs from the fat and place them, skin-side down, in an ovenproof frying pan. Roast for 30-40 mins, turning halfway through, until brown and crisp. Serve with the reheated gravy, a crisp salad and some crisp golden ptoatoes.",
    youtube: "https://www.youtube.com/watch?v=MHhLJqghY-o",
    image: "https://www.themealdb.com/images/media/meals/wvpvsu1511786158.jpg",
    description:
      "Duck confit is a French dish made with the whole duck. In Gascony, according to the families perpetuating the tradition of duck confit, all the pieces of duck are used to produce the meal.",
    cookingTime: 50,
    difficulty: "Medium",
    created_by: "Admin",
    country: "France",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Egg Drop Soup",
    ingredients: [
      "Chicken Stock: 3 cups",
      "Salt: 1/4 tsp",
      "Sugar: 1/4 tsp",
      "Pepper: pinch",
      "Sesame Seed Oil: 1 tsp",
      "Peas: 1/3 cup",
      "Mushrooms: 1/3 cup",
      "Cornstarch: 1 tbs",
      "Water: 2 tbs",
      "Spring Onions: 1/4 cup",
    ],
    instructions:
      "In a wok add chicken broth and wait for it to boil. Next add salt, sugar, white pepper, sesame seed oil. When the chicken broth is boiling add the vegetables to the wok. To thicken the sauce, whisk together 1 Tablespoon of cornstarch and 2 Tablespoon of water in a bowl and slowly add to your soup until it's the right thickness. Next add 1 egg slightly beaten with a knife or fork and add it to the soup slowly and stir for 8 seconds Serve the soup in a bowl and add the green onions on top.",
    youtube: "https://www.youtube.com/watch?v=9XpzHm9QpZg",
    image: "https://www.themealdb.com/images/media/meals/1529446137.jpg",
    description:
      "Egg drop soup (Chinese: 蛋花湯; pinyin: Dànhuātāng) is a Chinese soup of wispy beaten eggs in chicken broth.",
    cookingTime: 10,
    difficulty: "Easy",
    created_by: "Admin",
    country: "China",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Egyptian Fatteh",
    ingredients: [
      "Beef: 1lb",
      "Onion: 1",
      "Chicken Stock Cube: 1",
      "Tomatoes: 2",
      "Garlic Clove: 4",
      "Tomato Puree: 1 tbs",
      "Rice: 2 cups",
      "Noodles: 1/4 cup",
      "Butter: 1/4 cup",
      "Olive Oil: 2 cups",
      "Pita Bread: 1",
      "Cumin: 1 tbs",
      "White Wine Vinegar: 1 tbs",
      "Salt",
      "Pepper",
    ],
    instructions:
      "To prepare bread for bottom of dish: Take pita bread and rip into bite size pieces. In a frying pan, add about a 1/4 stick of butter, add bread pieces and fry until golden brown and crisp. Put these pieces in a glass baking dish, preferably a square sized dish. Set aside. Then add to same pan, a little more butter, salt, approximately 2 cloves of crushed fresh garlic, and a teaspoon or so of cumin stir around a bit until you can smell aroma, then add fried bread pieces to this mixture, stir to coat bread and put back into glass baking dish. Set aside. To prepare meat: put some butter in a pot, stir fry meat until brown, add 1 onion quartered, salt & pepper, 1 cube of chicken bouillon and water to cover meat. Bring to a boil, turn down to simmer, cover and cook until tender, approximately 2 hours. After meat has cooled, take out chunks of meat and put in a bowl, set aside. Reserve soup from the meat separately. To prepare the rice: Put some butter into a pot, add shareya (fideo noodles) like a handful or so, keep stirring until golden brown, not too dark, but very golden. Then add two cups of rice, stir a little bit until some of the rice turns an opaque white. Add 2-1/4 cups of water and salt to taste. Bring to a boil, cover and turn down to simmer, cook until tender. Test the rice tenderness after about 35 minutes. Now take some of the soup from meat and add to the top of the bread pieces in baking dish to saturate.Add cooked rice on top of bread pieces. Slowly spoon remainder of soup onto rice, looking at glass dish sides to see level of soup, should reach just to top of rice, don’t worry, this doesn’t have to be exact. Now you’re ready to make the sauce and fry the meat to put on top. To prepare red sauce: In a pan, add a little oil or butter, crushed tomato, a half teaspoon of tomato paste, salt & pepper, 2 cloves of fresh crushed garlic and cumin. Add also approximately 3 tablespoons of vinegar, stir this until you smell aroma and it is a bit smooth. It should be a bit thick, not watery, but if too thick you can add a bit of water. Spread with a wooden spoon atop the rice to cover. To fry meat: In a pan add a bit of butter or oil, the meat, just a touch of tomato paste, about a tablespoon of fresh crushed garlic, salt & pepper, a teaspoon of cumin. Cook until meat is golden fried. Spoon this atop the rice and serve. Enjoy!",
    youtube: "https://www.youtube.com/watch?v=WLuOHkDE4A4",
    image: "https://www.themealdb.com/images/media/meals/rlwcc51598734603.jpg",
    description:
      "Fatteh is an Egyptian and Levantine dish consisting of pieces of fresh, toasted, grilled, or stale flatbread covered with other ingredients that vary according to region.",
    cookingTime: 190,
    difficulty: "Medium",
    created_by: "Admin",
    country: "Egypt",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Fish fofos",
    ingredients: [
      "Haddock: 600g",
      "Potatoes: 300g",
      "Green Chilli: 1 chopped",
      "Coriander: 3 tbs",
      "Cumin Seeds: 1 tsp",
      "Pepper: 1/2 tsp",
      "Garlic: 3 cloves",
      "Ginger: 2 pieces",
      "Flour: 2 tbs",
      "Eggs: 3",
      "Breadcrumbs: 75g",
      "Vegetable Oil: For frying",
    ],
    instructions:
      "STEP 1 Put the fish into a lidded pan and pour over enough water to cover. Bring to a simmer and gently poach for 10 minutes over a low heat with the lid on. Drain and flake the fish. STEP 2 Put the fish, potato, green chilli, coriander, cumin, black pepper, garlic and ginger in a large bowl. Season, add the rice flour, mix well and break in 1 egg. Stir the mixture and divide into 15, then form into small logs. Break the remaining eggs into a bowl and whisk lightly. Put the breadcrumbs into another bowl. Dip each fofo in the beaten egg followed by the breadcrumb mixture. Chill for 20 minutes. STEP 3 Heat 1cm of oil in a large frying pan over a medium heat. Fry the fofos in batches for 2 minutes on each side, turning gently to get an even golden brown colour all over. Drain on kitchen paper and repeat with the remaining fofos. STEP 4 For the onion salad, mix together the onion, coriander and lemon juice with a pinch of salt. Serve with the fofos and mango chutney.",
    youtube: "https://www.youtube.com/watch?v=YXUZHK2PrV8",
    image: "https://www.themealdb.com/images/media/meals/a15wsa1614349126.jpg",
    description:
      "These fish croquettes are based on the Portuguese fofos de bacalhau, made using salt cod. Goans have adapted this using boneless fish, potatoes, ground spices and chilli",
    cookingTime: 65,
    difficulty: "Hard",
    created_by: "Admin",
    country: "Portugal",
    category: "Seafood",
    vegetarian: false,
  },
  {
    name: "Home-made Mandazi",
    ingredients: [
      "Self-raising Flour: 750g",
      "Sugar: 6 tablespoons",
      "Eggs: 2",
      "Milk: 1 cup",
    ],
    instructions:
      "This is one recipe a lot of people have requested and I have tried to make it as simple as possible and I hope it will work for you. Make sure you use the right flour which is basically one with raising agents. Adjust the amount of sugar to your taste and try using different flavours to have variety whenever you have them. You can use Coconut milk instead of regular milk, you can also add desiccated coconut to the dry flour or other spices like powdered cloves or cinnamon. For “healthy looking” mandazis do not roll the dough too thin before frying and use the procedure I have indicated above. 1. Mix the flour,cinnamon and sugar in a suitable bowl. 2. In a separate bowl whisk the egg into the milk 3. Make a well at the centre of the flour and add the milk and egg mixture and slowly mix to form a dough. 4. Knead the dough for 3-4 minutes or until it stops sticking to the sides of the bowl and you have a smooth surface. 5. Cover the dough with a damp cloth and allow to rest for 15 minutes. 6. Roll the dough on a lightly floured surface into a 1cm thick piece. 7. Using a sharp small knife, cut the dough into the desired size setting aside ready for deep frying. 8. Heat your oil in a suitable pot and gently dip the mandazi pieces to cook until light brown on the first side then turn to cook on the second side. 9. Serve them warm or cold",
    youtube:
      "https://www.youtube.com/watch?v=oWk0-7_hxZE&ab_channel=ChefRaphael",
    image: "https://www.themealdb.com/images/media/meals/thazgm1555350962.jpg",
    description:
      "Maandazis are Kenyan food which are made of all purpose flour. they are perfect for breakfast with a cup of tea. they can also go well as an accompaniment to many meal especially grilled meat. Enjoy!!",
    cookingTime: 60,
    difficulty: "Medium",
    created_by: "Admin",
    country: "Kenya",
    category: "Breakfast",
    vegetarian: true,
  },
  {
    name: "Kafteji",
    ingredients: [
      "Potatoes: 5 Large",
      "Olive Oil: 2 tbs",
      "Green Pepper: 1",
      "Onions: 5",
      "Ras el hanout: 1 tbs",
      "Pumpkin: 500g",
      "Eggs: 24 Skinned",
      "Salt",
      "Pepper",
    ],
    instructions:
      "Peel potatoes and cut into 5cm cubes. Pour 1-2 cm of olive oil into a large pan and heat up very hot. Fry potatoes until golden brown for 20 minutes, turning from time to time. Place on kitchen paper to drain. Cut the peppers in half and remove seeds. Rub a little olive oil on them and place the cut side down on a baking tray. Place them under the grill. Grill until the skin is dark and bubbly. While the peppers are still hot, put them into a plastic sandwich bag and seal it. Take them out after 15 minutes and remove skins. In the meantime, heat more olive oil another pan. Peel the onions and cut into thin rings. Fry for 15 minutes until golden brown, turning them often. Add the Ras el hanout at the end. Cut the pumpkin into 5cm cubes and fry in the same pan you used for the potatoes for 10-15 minutes until it is soft and slightly browned. Place on kitchen paper. Pour the remaining olive oil out of the pan and put all the cooked vegetables into the pan and mix. Whisk eggs and pour them over the vegetables. Put the lid on the pan so that the eggs cook. Put the contents of the pan onto a large chopping board, add salt and pepper and chopped and mix everything with a big knife.",
    youtube: "https://www.youtube.com/watch?v=-TFf-Zu-xQU",
    image: "https://www.themealdb.com/images/media/meals/1bsv1q1560459826.jpg",
    description:
      "Kafteji is something of a Tunisian poor man's food: various vegetables are fried separately and then fried with beaten egg and chopped up together with a large knife. One eats it as a baguette filling.",
    cookingTime: 90,
    difficulty: "Easy",
    created_by: "Admin",
    country: "Tunisia",
    category: "Main Course",
    vegetarian: true,
  },
  {
    name: "Kumpir",
    ingredients: [
      "Potatoes: 2 large",
      "Butter: 2 tbs",
      "Cheese: 150g",
      "Onion: 1 large",
      "Red Pepper: 1 large",
      "Red Chile Flakes: Pinch",
    ],
    instructions:
      "If you order kumpir in Turkey, the standard filling is first, lots of butter mashed into the potato, followed by cheese. There’s then a row of other toppings that you can just point at to your heart’s content – sweetcorn, olives, salami, coleslaw, Russian salad, allsorts – and you walk away with an over-stuffed potato because you got ever-excited by the choices on offer. Grate (roughly – you can use as much as you like) 150g of cheese. Finely chop one onion and one sweet red pepper. Put these ingredients into a large bowl with a good sprinkling of salt and pepper, chilli flakes (optional).",
    youtube: "https://www.youtube.com/watch?v=IEDEtZ4UVtI",
    image: "https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg",
    description:
      "Kumpir is a very simple and popular street food dish in Turkey. It is actually a Turkish version of baked potato or jacket potato as it is called in the UK. Unlike the jacket potato, which is usually served with cheese, beans and butter, there are many different side dishes to go with the potato.",
    cookingTime: 75,
    difficulty: "Easy",
    created_by: "Admin",
    country: "Turkey",
    category: "Side dish",
    vegetarian: true,
  },
  {
    name: "Lamb tomato and sweet spices",
    ingredients: [
      "olive oil: 2 tbsp",
      "ginger: 4cm piece finely chopped",
      "garlic: 2 cloves peeled and chopped",
      "tomatoes: 800g peeled and chopped",
      "lemon juice: 2 tbsp",
      "caster sugar: 1 tsp",
      "vine leaves: 50",
      "fennel bulb: 1 large",
      "lamb mince: 400g",
      "onion: 1 medium",
      "potato: 1 small peeled and coarsely grated",
      "basmati rice: 2 tbsp",
      "chopped parsley: 2 tbsp",
      "coriander: 2 tbsp chopped",
      "lemon juice: 1 tbsp",
      "garlic: 2 cloves",
      "clove: ½ tsp ground",
      "cinnamon: ½ tsp ground",
      "tomatoes: 2 medium",
    ],
    instructions:
      "Use pickled vine leaves here, preserved in brine. Small delicate leaves are better than the large bristly ones but, if only large leaves are to hand, then trim them to roughly 12 by 12 cms so that you don't get too many layers of leaves around the filling. And remove any stalks. Drain the preserved leaves, immerse them in boiling water for 10 minutes and then leave to dry on a tea towel before use. Basmati rice with butter and pine nuts is an ideal accompaniment. Couscous is great, too. Serves four. First make the filling. Put all the ingredients, apart from the tomatoes, in a bowl. Cut the tomatoes in half, coarsely grate into the bowl and discard the skins. Add half a teaspoon of salt and some black pepper, and stir. Leave on the side, or in the fridge, for up to a day. Before using, gently squeeze with your hands and drain away any juices that come out. To make the sauce, heat the oil in a medium pan. Add the ginger and garlic, cook for a minute or two, taking care not to burn them, then add the tomato, lemon juice and sugar. Season, and simmer for 20 minutes. While the sauce is bubbling away, prepare the vine leaves. Use any torn or broken leaves to line the base of a wide, heavy saucepan. Trim any leaves from the fennel, cut it vertically into 0.5cm-thick slices and spread over the base of the pan to cover completely. Lay a prepared vine leaf (see intro) on a work surface, veiny side up. Put two teaspoons of filling at the base of the leaf in a 2cm-long by 1cm-wide strip. Fold the sides of the leaf over the filling, then roll it tightly from bottom to top, in a cigar shape. Place in the pan, seam down, and repeat with the remaining leaves, placing them tightly next to each other in lines or circles (in two layers if necessary). Pour the sauce over the leaves (and, if needed, add water just to cover). Place a plate on top, to weigh the leaves down, then cover with a lid. Bring to a boil, reduce the heat and cook on a bare simmer for 70 minutes. Most of the liquid should evaporate. Remove from the heat, and leave to cool a little - they are best served warm. When serving, bring to the table in the pan - it looks great. Serve a few vine leaves and fennel slices with warm rice. Spoon the braising juices on top and garnish with coriander.",
    "'youtube": "https://www.youtube.com/watch?v=vaZb1MnFBgA",
    image: "https://www.themealdb.com/images/media/meals/qtwtss1468572261.jpg",
    description:
      "Sofrito is a meat (lamb, beef, chicken) stew sautéed with potatoes, garlic, turmeric, and cardamom and simmered in a small volume of water or stock with an acidic agent (sour plum juice, vinegar, or lemon juice), or braised with all these ingredients without prior sautéing.",
    cookingTime: 190,
    difficulty: "Hard",
    created_by: "Admin",
    country: "Morocco",
    category: "Main Course",
    vegetarian: false,
  },
  {
    name: "Leblebi Soup",
    ingredients: [
      "Olive Oil: 2 tbs",
      "Onion: 1 medium finely diced",
      "Chickpeas: 250g",
      "Vegetable Stock: 1.5L",
      "Cumin: 1 tsp ",
      "Garlic: 5 cloves",
      "Salt: 1/2 tsp",
      "Harissa Spice: 1 tsp ",
      "Pepper: Pinch",
      "Lime: 1/2",
    ],
    instructions:
      "Heat the oil in a large pot. Add the onion and cook until translucent. Drain the soaked chickpeas and add them to the pot together with the vegetable stock. Bring to the boil, then reduce the heat and cover. Simmer for 30 minutes. In the meantime toast the cumin in a small ungreased frying pan, then grind them in a mortar. Add the garlic and salt and pound to a fine paste. Add the paste and the harissa to the soup and simmer until the chickpeas are tender, about 30 minutes. Season to taste with salt, pepper and lemon juice and serve hot.",
    youtube: "https://www.youtube.com/watch?v=BgRifcCwinY",
    image: "https://www.themealdb.com/images/media/meals/x2fw9e1560460636.jpg",
    description:
      "Lablabi or Lablebi is a Tunisian dish based on chick peas in a thin garlic and cumin-flavoured broth, served over small pieces of stale crusty bread.",
    cookingTime: 210,
    difficulty: "Medium",
    created_by: "Admin",
    country: "Tunisia",
    category: "Main Course",
    vegetarian: true,
  },
])
.then(()=>{
  console.log('seed done')
mongoose.connection.close()
})
.catch(()=>{
  console.log('seed failed')
  mongoose.connection.close()
})